[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "simulat"
version = "0.18.0"
description = "A tile-based roguelike-like life simulation game."
authors = [
    {name = "Artur Borecki", email = "me@pufereq.pl"},
]
dependencies = [
    "pygame-ce",
    "pyyaml",
    "cerberus",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "GPL-3.0+"}

[tool.pdm]
distribution = true

[tool.pdm.scripts]
simulat = {call = "simulat.__main__:main"}

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.14.0",
    "pytest-github-actions-annotate-failures>=0.2.0",
]
bump = [
    "git-cliff>=2.6.0",
    "python-semantic-release>=9.8.8",
]
lint = [
    "black>=24.8.0",
    "isort>=5.13.2",
]

[tool.pytest.ini_options]
addopts = [
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=100",
]

[tool.coverage.run]
omit = [
    "simulat/__init__.py",
    "tests/*",
]

[tool.semantic_release]
version_variables = ["simulat/__init__.py:__version__"]
version_toml = ["pyproject.toml:project.version"]
build_command_env = []
commit_message = "chore(release): {version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "{version}"

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0